---
title: "Wybory prezydenckie 2020 - II tura"
author: "Radosław Pałkowski"
date: "15 07 2020"
output:
  md_document:
    variant: markdown_github
  html_document: default
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=6, fig.path='wykresy/',
                      fig.align='center', dpi = 300, tidy=TRUE,
                      echo=FALSE, warning=FALSE, message=FALSE)
```

---


```{r pakiety, warning=FALSE, results='hide', message=FALSE}
library(tidyverse)
library(sf)
library(stringr)
```

```{r dane, warning=FALSE, results='hide', message=FALSE}
dane <- read_csv2("wyniki_gl_na_kand_po_gminach_utf8.csv")

# plik shp z mapą Polski z podziałem według gmin 
# plik "jednostki_ewidencyjne" - zawiera szczegółowy podział Warszawy na dzielnice 

shp_gminy <- "./pliki_shp/Jednostki_ewidencyjne.shp"

shp_wojewodztwa <- "./pliki_shp/Województwa.shp"

```


```{r przygotowanie mapy i danych, warning=FALSE, results='hide', message=FALSE}

# mapa Polski według gmin  ------------------------------------------------

# plik shp jest dosyć duży - stąd wybrane są tylko kolumny JPT_KOD_JE (to nic innego jak kod TERYT 
# więc tylko zmiana nazwy) oraz geometry czyli listy z współrzędnymi granic obszarów 

# Należy poprawić Zieloną Górę (gminę miejską, nie miasto) oraz Łódź i Kraków - które są podzielone na 
# dzielnice natomiast wyniki z PKW traktują to jako ten sam kod TERYT 

mapa_gminy <- read_sf(shp_gminy) %>%
  select(TERYT = JPT_KOD_JE, geometry, JPT_NAZWA_) %>%
  mutate(TERYT = str_sub(TERYT, 1, 6)) %>%  # skrócenie kodu teryt do 6 cyfr 
  mutate(TERYT = if_else(str_detect(TERYT, "080910"), "086201", TERYT),
         TERYT = if_else(str_detect(TERYT, "106102"), "106101", TERYT),
         TERYT = if_else(str_detect(TERYT, "106103"), "106101", TERYT),
         TERYT = if_else(str_detect(TERYT, "106104"), "106101", TERYT),
         TERYT = if_else(str_detect(TERYT, "106105"), "106101", TERYT),
         TERYT = if_else(str_detect(TERYT, "106106"), "106101", TERYT),
         TERYT = if_else(str_detect(TERYT, "126102"), "126101", TERYT),
         TERYT = if_else(str_detect(TERYT, "126103"), "126101", TERYT),
         TERYT = if_else(str_detect(TERYT, "126104"), "126101", TERYT),
         TERYT = if_else(str_detect(TERYT, "126105"), "126101", TERYT))


mapa_woj <- read_sf(shp_wojewodztwa) %>% 
  select(TERYT = JPT_KOD_JE, geometry, JPT_NAZWA_) %>% 
  mutate(TERYT = str_sub(TERYT, 1, 6))


# drobne zmiany w zbiorze danych - str_sub zmienia długość kodu TERYT na równą długość dla wszystkich 
# użycie ` ` pozwala na wybranie nazw zmiennych ze spacją  

dane <- dane %>% 
  mutate(`Kod TERYT` = str_sub(`Kod TERYT`, 1, 6))


```



```{r frekwencja, warning=FALSE, results='hide', message=FALSE}

# wybór odpowiednich kolumn + zmiana nazw i obliczenie frekwencji 
frekwencja <- dane[, c(2, 8, 10)] %>% 
  set_names("TERYT", "uprawnieni_wyborcy", "wydane_karty") %>% 
  group_by(TERYT) %>% 
  summarise(uprawnieni_wyborcy = sum(uprawnieni_wyborcy), 
            wydane_karty = sum(wydane_karty)) %>% 
  ungroup() %>% 
  mutate(frekwencja_proc = (wydane_karty / uprawnieni_wyborcy)*100)


# frekwencja do poprawy - albo liczona razem z korespondencyjnym albo oddzielnie
# (trzeba odjąć od głosów wyjętych)

frekwencja_do_mapy <- left_join(mapa_gminy, 
                             frekwencja %>% 
                               select(TERYT, frekwencja_proc), 
                             by = "TERYT")


frekwencja_mapa <- ggplot() +
  geom_sf(data = frekwencja_do_mapy, aes(fill = frekwencja_proc),  size = 0.1, color = "gray90") +
  geom_sf(data = mapa_woj, size = 0.25, color = "gray30", fill = NA) +
  geom_sf_text(data = frekwencja_do_mapy %>% filter(frekwencja_proc == 0),
               aes(label = JPT_NAZWA_), colour = "black", size = 1.25, fontface = "bold", 
               position = position_nudge(y = -0.1)) +
  scale_fill_distiller(palette = "Greens", direction = 1) +
  theme_void() + 
  theme(legend.position = c(0.20, 0.10), legend.direction = "horizontal",
        legend.title = element_text(size = 7),
        legend.text = element_text(size = 6),
        legend.key.size = unit(10, "points"),
        plot.title = element_text(face = "bold", size = 11),
        plot.subtitle = element_text(size = 9),
        plot.caption = element_text(size = 7, colour = "grey30"), 
        plot.margin = unit(c(5,3,5,3), "points")) +
  labs(title = "Frekwencja w wyborach prezydenckich 2020 (II tura) na poziomie gmin",
       subtitle = "Tylko lokale wyborcze, bez głosowania korespondencyjnego\n W gminach Baranów i Marklowice przeprowadzono wyłącznie głosowanie korespondencyjne",
       caption = "Radosław Pałkowski \n github.com/rpalkowski", 
       fill = "Frekwencja (%)")

```


```{r frekwencja_mapa_II_tura}
frekwencja_mapa
```


```{r głosy ważne i nieważne, warning=FALSE, results='hide', message=FALSE}

# głosy ważne i nieważne --------------------------------------------------



glosy <- dane[, c(2, 20, 24, 28, 22)] %>% 
  set_names("TERYT", "glosy_oddane", "glosy_niewazne", "glosy_wazne", "karty_niewazne") %>% 
  group_by(TERYT) %>% 
  summarise(glosy_oddane = sum(glosy_oddane),
            glosy_niewazne = sum(glosy_niewazne), 
            glosy_wazne = sum(glosy_wazne), 
            karty_niewazne = sum(karty_niewazne)) %>% 
  ungroup() %>% 
  mutate(glosy_niewazne_proc = (glosy_niewazne / glosy_oddane)*100,
         glosy_wazne_proc = (glosy_wazne / glosy_oddane)*100,
         karty_niewazne_proc = (karty_niewazne / glosy_oddane)*100)

# połączenie z tabelą ze współrzędnymi
glosy_mapa <- left_join(mapa_gminy, glosy, by = "TERYT")


glosy_niewazne_mapa <- glosy_mapa %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = glosy_niewazne_proc),  size = 0.10, color = "gray95") +
  geom_sf(data = mapa_woj, size = 0.2, color = "gray30", fill = NA) +
  scale_fill_distiller(palette = "Reds", direction = 1) +
  theme_void() +
  theme(legend.position = c(0.20, 0.10), legend.direction = "horizontal",
      legend.title = element_text(size = 7),
      legend.text = element_text(size = 6),
      legend.key.size = unit(10, "points"),
      plot.title = element_text(face = "bold", size = 11),
      plot.subtitle = element_text(size = 9),
      plot.caption = element_text(size = 7, colour = "grey30"), 
      plot.margin = unit(c(5,3,5,3), "points")) +
  labs(title = "Głosy nieważne w wyborach prezydenckich 2020 (II tura) na poziomie gmin",
       caption = "Radosław Pałkowski \n github.com/rpalkowski", 
       fill = "Głosy nieważne (%)")
  
```

```{r glosy_niewazne_II_tura}
glosy_niewazne_mapa
```


```{r zwycięzcy według gmin, warning=FALSE, results='hide', message=FALSE}

# zwycięzcy według gmin ---------------------------------------------------

wyniki <- dane[, c(2, 28, 29:30)] %>%
  rename(TERYT = `Kod TERYT`) %>% 
  gather(3:4, key = "kandydat", value = "glosy") %>%
  group_by(TERYT, kandydat) %>% 
  summarise(glosy_na_kandydata = sum(glosy)) %>% 
  ungroup() %>% 
  left_join(glosy %>% select(TERYT, glosy_wazne), by = "TERYT") %>% 
  mutate(glosy_na_kandydata_proc = (glosy_na_kandydata / glosy_wazne)*100)

wyniki_mapa <- left_join(mapa_gminy, 
                       wyniki %>% 
                         group_by(TERYT) %>% 
                         top_n(1, glosy_na_kandydata), 
                      by = "TERYT")


mapa_zwyciezcy_gminy <- wyniki_mapa %>%
  ggplot() +
  geom_sf(aes(fill = kandydat), size = 0.1, color = "gray95") +
  geom_sf(data = mapa_woj, size = 0.25, color = "gray30", fill = NA) +
  scale_fill_manual(values = c("dodgerblue3", "cyan3")) +
  theme_void() + 
  theme(legend.position = "bottom", legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(size = 8),
        legend.key.size = unit(10, "points"),
        plot.title = element_text(face = "bold", size = 11),
        plot.subtitle = element_text(size = 9),
        plot.caption = element_text(size = 7, colour = "grey30"), 
        plot.margin = unit(c(5,5,5,5), "points")) +
  labs(title = "Kandydaci z największą liczbą głosów na poziomie gmin",
       subtitle = "II tura, 12.07.2020",
       caption = "Radosław Pałkowski \n github.com/rpalkowski",
       fill = "", color="")
```

```{r zwyciezcy_gminy_II_tura}
mapa_zwyciezcy_gminy
```

```{r poparcie, warning=FALSE, results='hide', message=FALSE}
poparcie <- left_join(mapa_gminy, wyniki, by = "TERYT")
```


```{r poparcie_ad_rt_razem, warning=FALSE, results='hide', message=FALSE}

# dwójka kandydatów razem na jednym wykresie 
mapa_poparcie_proc <- poparcie %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = glosy_na_kandydata_proc), size = 0.1, color = "gray90") +
  geom_sf(data = mapa_woj, size = 0.25, color = "gray30", fill = NA) +
  scale_fill_distiller(palette = "Blues", direction = 1) +
  facet_wrap(~kandydat) +
  theme_void() + 
  theme(legend.position = "bottom", legend.direction = "horizontal",
        legend.title = element_text(size = 9),
        legend.text = element_text(size = 8),
        legend.key.size = unit(15, "points"),
        plot.title = element_text(face = "bold", size = 20),
        plot.subtitle = element_text(size = 9),
        plot.caption = element_text(size = 7, colour = "grey30"), 
        plot.margin = unit(c(5,5,5,5), "points")) +
  labs(title = "Poparcie dla Andrzeja Dudy i Rafała Trzaskowskiego (II tura)",
       subtitle = " ", 
       caption = "Radosław Pałkowski \n github.com/rpalkowski",
       fill = "Głosy (%)")

```

```{r poparcie_proc_II_tura, fig.width=12, fig.height=6}
mapa_poparcie_proc
```



```{r warning=FALSE, results='hide', message=FALSE}

# poparcie dla Rafała Trzaskowskiego 
mapa_poparcie_proc_rt <- poparcie %>%
  filter(kandydat == "Rafał Kazimierz TRZASKOWSKI") %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = glosy_na_kandydata_proc), size = 0.1, color = "gray100") +
  geom_sf(data = mapa_woj, size = 0.25, color = "gray30", fill = NA) +
  scale_fill_distiller(palette = "Blues", direction = 1) +
  theme_void() +
  theme(legend.position = c(0.20, 0.10), legend.direction = "horizontal",
        legend.title = element_text(size = 7),
        legend.text = element_text(size = 6),
        legend.key.size = unit(10, "points"),
        plot.title = element_text(face = "bold", size = 11),
        plot.subtitle = element_text(size = 9),
        plot.caption = element_text(size = 7, colour = "grey30"), 
        plot.margin = unit(c(5,5,5,5), "points")) +
  labs(title = "Poparcie na poziomie gmin - Rafał Kazimierz TRZASKOWSKI",
       subtitle = "II tura, 12.07.2020",
       caption = "Radosław Pałkowski \n github.com/rpalkowski",
       fill = "Procent głosów")
```

```{r poparcie_proc_rt_II_tura}
mapa_poparcie_proc_rt
```


```{r warning=FALSE, results='hide', message=FALSE}

# poparcie dla Andrzeja Dudy 
mapa_poparcie_proc_ad = poparcie %>%
  filter(kandydat == "Andrzej Sebastian DUDA") %>% 
  ggplot() +
  geom_sf(mapping = aes(fill = glosy_na_kandydata_proc), size = 0.1, color = "gray100") +
  geom_sf(data = mapa_woj, size = 0.25, color = "gray30", fill = NA) +
  scale_fill_distiller(palette = "Blues", direction = 1) +
  theme_void() +
  theme(legend.position = c(0.20, 0.10), legend.direction = "horizontal",
        legend.title = element_text(size = 7),
        legend.text = element_text(size = 6),
        legend.key.size = unit(10, "points"),
        plot.title = element_text(face = "bold", size = 11),
        plot.subtitle = element_text(size = 9),
        plot.caption = element_text(size = 7, colour = "grey30"), 
        plot.margin = unit(c(5,5,5,5), "points")) +
  labs(title = "Poparcie na poziomie gmin - Andrzej Sebastian DUDA",
       subtitle = "II tura, 12.07.2020",
       caption = "Radosław Pałkowski \n github.com/rpalkowski",
       fill = "Procent głosów")
```


```{r poparcie_proc_ad_II_tura}
mapa_poparcie_proc_ad
```
